# Generated by Django 4.2.3 on 2025-03-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/400x200?text=Course+Image'),
        ),
    ]
